#!/usr/bin/env bash

set -e

TMPFS_DIR="/mnt/tmpfs"
DEFAULT_SIZE="2048M"

sudo mkdir -p "$TMPFS_DIR"
sudo chmod 777 "$TMPFS_DIR"

[[ $# -eq 0 ]] && argument="create" || argument="$1"

case "$argument" in
"create")
  if mountpoint -q "$TMPFS_DIR"; then
    echo -ne "Do you really want to mount /mnt/tmpfs again (Y/n)? "
    read -r answer
    if [[ "$answer" != "${answer#[Nn]}" ]]; then
      exit 0
    fi
  fi
  sudo mount -t tmpfs -o size="$DEFAULT_SIZE" tmpfs "$TMPFS_DIR"
  echo "Mounted file system at $TMPFS_DIR with size $DEFAULT_SIZE"
  ;;
"resize")
  if mountpoint -q "$TMPFS_DIR"; then
    if [ $# -eq 2 ]; then
      sudo mount -o remount,size="$2M" "$TMPFS_DIR"
      echo "Resized file system to $2M"
    else
      echo "Specify size in megabytes" >&2
      exit 1
    fi
  else
    echo "Nothing to resize, mount it first" >&2
    exit 1
  fi
  ;;
"unmount")
  if mountpoint -q "$TMPFS_DIR"; then
    sudo umount -f "$TMPFS_DIR"
    echo "Unmounted file system at $TMPFS_DIR"
  else
    echo "Nothing to unmount, mount it first" >&2
    exit 1
  fi
  ;;
*)
  echo "Invalid argument: $1, excepted create, resize <size>, unmount" >&2
  exit 1
  ;;
esac
